version: '3.3'
services:
    app:
        volumes:
            - ./credentials:/app/credentials
            - ./instances:/app/instances
            - ./logs:/app/logs
            - ./maps:/app/maps
        environment:
            - RPP_DISCORD_CLIENT_ID=111....1111
            - RPP_DISCORD_TOKEN=token
            - RPP_STEAM_API_KEY=your_steam_api_key_here
        container_name: rpp
        image: ghcr.io/alexemanuelol/rustplusplus
